// Genere automatiquement a partir de public/work/affiches.
// Pour regenerer : deposer de nouvelles images puis relancer l'optimisation.
import type { Project } from "./data";

export const affiches: Project[] = [
  { title: "15 mai AHTS", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-01.webp", ratio: "square" },
  { title: "Affiche Yam auto", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-02.webp", ratio: "square" },
  { title: "AHTS Avril", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-03.webp", ratio: "square" },
  { title: "Ahts bon mois de juillet", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-04.webp", ratio: "square" },
  { title: "AHTS confiance", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-05.webp", ratio: "square" },
  { title: "Ahts fevrier", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-06.webp", ratio: "square" },
  { title: "AHTS question", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-07.webp", ratio: "square" },
  { title: "Ahts ramadan", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-08.webp", ratio: "square" },
  { title: "Ahts SERVICE COMIQUE", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-09.webp", ratio: "square" },
  { title: "Azaf", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-10.webp", ratio: "square" },
  { title: "AZAF 1er Mai", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-11.webp", ratio: "square" },
  { title: "Azaf hts tabaski", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-12.webp", ratio: "square" },
  { title: "Azaf noel", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-13.webp", ratio: "square" },
  { title: "Bethel digital first flyers", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-14.webp", ratio: "square" },
  { title: "Bon dimanche delta survey", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-15.webp", ratio: "square" },
  { title: "Bon mardi", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-16.webp", ratio: "square" },
  { title: "Bon mois de juillet", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-17.webp", ratio: "square" },
  { title: "Bonne année Nts", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-18.webp", ratio: "square" },
  { title: "Bonne fete RB", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-19.webp", ratio: "square" },
  { title: "Bonne journée NTS", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-20.webp", ratio: "square" },
  { title: "Bonne semaine AHTS", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-21.webp", ratio: "square" },
  { title: "Delta surveys bon weekend", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-22.webp", ratio: "square" },
  { title: "Delta surveys bonne semaine", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-23.webp", ratio: "square" },
  { title: "Deltasurveys", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-24.webp", ratio: "square" },
  { title: "Mockup delta surveys carte de visite", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-25.webp", ratio: "square" },
  { title: "Creation", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-26.webp", ratio: "square" },
  { title: "Dossier sur tech", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-27.webp", ratio: "square" },
  { title: "Creation", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-28.webp", ratio: "square" },
  { title: "Récupéré", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-29.webp", ratio: "square" },
  { title: "Srt frevrier", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-30.webp", ratio: "square" },
  { title: "Sur tech affiche", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-31.webp", ratio: "square" },
  { title: "Sur tech bonne semaine", category: "Affiches", tag: "Affiche", image: "/work/affiches/affiche-32.webp", ratio: "square" },
];
